- hosts: all
  tasks:
    - name: 'Permissão diretórios SSH'
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0700
      become: yes

    - name: 'Copia os aquivos SSH'
      copy:
        src: files/{{ item }}
        dest: /home/vagrant/.ssh/{{ item }}
        owner: vagrant
        group: vagrant
        mode: 0600
      with_items:
        - id_rsa
        - id_rsa.pub
      become: yes

    - name: 'Atualiza/instala os pacotes necessários para utilizar o repositório apt do Kubernetes'
      apt: 
        name:
          - apt-transport-https
          - ca-certificates curl
        state: latest
      become: yes

    - name: 'Download da chave de assinatura pública da Google Cloud'
      apt_key: 
        name: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: yes

    - name: 'Adiciona o repositório apt do Kubernetes'
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        update_cache: yes
      become: yes

    - name: 'Atualiza/instala os pacotes necessários para utilizar o repositório apt do Kubernetes'
      apt: 
        name: 
          - docker.io
          - kubelet
          - kubeadm
          - kubectl
        state: latest
      become: yes
